"use client";
import { useEffect, useRef, useState } from "react";
import { DragDropProvider, DragOverlay } from "@dnd-kit/react";
import { ArrowDownToLine, LockKeyhole, ChevronRight, Code2, Download, Eye, FileJson, FilePlus2, Layers3, Monitor, PanelLeft, PencilRuler, Redo2, Save, ShieldCheck, Smartphone, Tablet, Undo2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { useBuilder } from "@/core/store";
import { makeNode, registry } from "@/core/registry";
import { readDraft, writeDraft } from "@/core/persistence";
import { locate, validateDocument, type Target } from "@/core/validation";
import type { PageDocument, PageNode, Viewport } from "@/core/schema";
import { EditorContext, type DragSource } from "./editor-context";
import { Library } from "./library";
import { Canvas, moveSelected } from "./canvas";
import { Inspector } from "./inspector";

function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=window.document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportResponse(document:PageDocument,format:"zip"|"code"){const response=await fetch("/api/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({document,format})});if(!response.ok){const error=await response.json();throw new Error(error.error??"导出失败");}return response;}
function CodePanel(){const document=useBuilder(s=>s.document);const [tab,setTab]=useState("tsx");const [result,setResult]=useState<{code:string;files:string[]}|null>(null);const [error,setError]=useState("");
  useEffect(()=>{let active=true;exportResponse(document,"code").then(r=>r.json()).then(result=>{if(active)setResult(result);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[document]);
  return <section className="code-panel" aria-label="代码预览"><header><div><button className={tab==="tsx"?"active":""} onClick={()=>setTab("tsx")}><Code2 size={14}/> page.tsx</button><button className={tab==="dsl"?"active":""} onClick={()=>setTab("dsl")}><FileJson size={14}/> Page DSL</button></div><Button size="sm" variant="outline" onClick={()=>download(new Blob([JSON.stringify(document,null,2)],{type:"application/json"}),"page.dsl.json")}><Download size={13}/>导出 DSL</Button></header><pre tabIndex={0} aria-label={tab==="tsx"?"生成的 TSX":"Page DSL"}><code>{tab==="dsl"?JSON.stringify(document,null,2):error||result?.code||"正在校验并生成代码…"}</code></pre><footer><ShieldCheck size={14}/>{result?`独立 Next.js 项目 · ${result.files.length} 个文件 · 不包含编辑器依赖`:"生成中"}</footer></section>;
}
export function Builder(){const s=useBuilder();const [source,setSource]=useState<DragSource|null>(null);const [sourceNode,setSourceNode]=useState<PageNode|null>(null);const [target,setTarget]=useState<Target|null>(null);const [saving,setSaving]=useState(false);const [exporting,setExporting]=useState(false);const [newOpen,setNewOpen]=useState(false);const [renaming,setRenaming]=useState(false);const [pageName,setPageName]=useState("");const [helpOpen,setHelpOpen]=useState(false);const [libraryOpen,setLibraryOpen]=useState(false);const fileInput=useRef<HTMLInputElement>(null);const [pendingImport,setPendingImport]=useState<PageDocument|null>(null);
  useEffect(()=>{let active=true;readDraft().then(draft=>{if(!active)return;if(draft)useBuilder.getState().load(draft);else useBuilder.setState({ready:true});}).catch(error=>{if(active)useBuilder.setState({ready:true,loadError:true,message:`草稿加载失败，原数据未覆盖。${error instanceof Error?error.message:"请检查浏览器存储权限"}`});});return()=>{active=false;};},[]);
  useEffect(()=>{function beforeUnload(event:BeforeUnloadEvent){if(useBuilder.getState().dirty){event.preventDefault();event.returnValue="";}}window.addEventListener("beforeunload",beforeUnload);return()=>window.removeEventListener("beforeunload",beforeUnload);},[]);
  useEffect(()=>{function keyboard(e:KeyboardEvent){if((e.target as HTMLElement).closest("input,textarea,select,[contenteditable=true],[role=dialog]"))return;const s=useBuilder.getState();if(s.mode!=="edit")return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey)s.redoOnce();else s.undoOnce();}if(e.altKey&&(e.key==="ArrowUp"||e.key==="ArrowDown")){e.preventDefault();moveSelected(e.key==="ArrowUp"?-1:1);}if(e.key==="Escape"){s.select(null);setTarget(null);}}window.addEventListener("keydown",keyboard);return()=>window.removeEventListener("keydown",keyboard);},[]);
  async function save(){if(s.loadError||saving)return;setSaving(true);const snapshot=useBuilder.getState();const savedAt=new Date().toISOString();try{await writeDraft({document:snapshot.document,revision:snapshot.revision,viewport:snapshot.viewport,savedAt,history:{undo:snapshot.undo,redo:snapshot.redo}});useBuilder.setState({savedAt,dirty:useBuilder.getState().revision!==snapshot.revision,message:"已保存到当前浏览器，刷新后可恢复"});}catch(error){s.notify(`保存失败：${error instanceof Error?error.message:"浏览器存储不可用"}。更改仍保留在画布中，请导出 DSL 备份。`);}finally{setSaving(false);}}
  async function exportZip(){setExporting(true);try{const response=await exportResponse(s.document,"zip");download(await response.blob(),"composed-page.zip");s.notify("已导出独立 Next.js 项目");}catch(error){s.notify(`导出失败：${error instanceof Error?error.message:"请重试"}`);}finally{setExporting(false);}}
  function applyImport(document:PageDocument){s.load({document,revision:0,viewport:"desktop",savedAt:new Date().toISOString(),history:{undo:[],redo:[]}});useBuilder.setState({dirty:true,savedAt:null,message:"DSL 已导入，请保存草稿"});setPendingImport(null);setTarget(null);}
  return <EditorContext.Provider value={{source,sourceNode,target,chooseTarget:t=>{setTarget(t);s.select(t.parentId);s.notify("已选择插入位置，请在组件库点击要添加的组件");}}}><DragDropProvider
    onDragStart={event=>{const data=event.operation.source?.data as DragSource|undefined;if(!data)return;setSource(data);setSourceNode(data.nodeId?locate(s.document,data.nodeId)?.node??null:data.componentRef?makeNode(data.componentRef):null);}}
    onDragEnd={event=>{const dest=event.operation.target?.data.target as Target|undefined;if(!event.canceled&&dest&&sourceNode){const command=source?.nodeId?{type:"node.move" as const,nodeId:source.nodeId,target:dest}:{type:"node.insert" as const,node:sourceNode,target:dest};if(s.dispatch(command)){s.select(sourceNode.id);setTarget(null);}}else if(!event.canceled)s.notify("未找到放置区域，组件保持原位置");setSource(null);setSourceNode(null);}}
  ><div className="builder-app">
    <header className="app-header"><div className="app-brand"><span className="app-logo"><Layers3 size={19}/></span><strong>Composer</strong><span className="brand-divider"/><span className="project-label">我的项目</span><ChevronRight size={13}/><button className="page-name" onClick={()=>{setPageName(s.document.name);setRenaming(true);}}>{s.document.name}<span className="draft-badge">草稿</span></button></div><div className="header-actions"><span className="save-state"><span className={s.dirty?"unsaved-dot":"saved-dot"}/>{s.dirty?"未保存更改":s.savedAt?"已保存到本地":"本地草稿"}</span><Button variant="outline" size="sm" disabled={!s.ready||saving||s.loadError} onClick={save}><Save size={14}/>{saving?"保存中…":"保存"}</Button><Button variant="outline" size="sm" disabled={!s.ready||s.loadError} onClick={()=>download(new Blob([JSON.stringify(s.document,null,2)],{type:"application/json"}),"page.dsl.json")}><FileJson size={14}/>导出 DSL</Button><Button size="sm" disabled={!s.ready||exporting||s.loadError} onClick={exportZip}><ArrowDownToLine size={14}/>{exporting?"正在导出…":"导出代码"}</Button><span className="header-avatar">JD</span></div></header>
    <div className="editor-toolbar"><div className="toolbar-start"><button className="icon-button mobile-library-toggle" aria-label="打开组件库" onClick={()=>setLibraryOpen(true)}><PanelLeft size={16}/></button><span className="shell-tag"><PanelLeft size={14}/>Contextual Shell<LockKeyhole size={10}/></span><span className="tool-divider"/><button className="icon-button" title="撤销 ⌘Z" aria-label="撤销" disabled={!s.undo.length||s.loadError} onClick={s.undoOnce}><Undo2 size={15}/></button><button className="icon-button" title="重做 ⌘⇧Z" aria-label="重做" disabled={!s.redo.length||s.loadError} onClick={s.redoOnce}><Redo2 size={15}/></button></div><div className="editor-modes" aria-label="编辑器模式">{([{id:"edit",name:"设计",Icon:PencilRuler},{id:"preview",name:"预览",Icon:Eye},{id:"code",name:"代码",Icon:Code2}] as const).map(({id,name,Icon})=><button key={id} className={s.mode===id?"active":""} aria-pressed={s.mode===id} onClick={()=>{s.setMode(id);setTarget(null);}}><Icon size={13}/>{name}</button>)}</div><div className="viewport-controls" aria-label="预览视口">{([{id:"desktop",name:"桌面",Icon:Monitor},{id:"tablet",name:"平板",Icon:Tablet},{id:"mobile",name:"手机",Icon:Smartphone}] as {id:Viewport;name:string;Icon:typeof Monitor}[]).map(({id,name,Icon})=><button key={id} className={`icon-button ${s.viewport===id?"active":""}`} aria-label={name} aria-pressed={s.viewport===id} title={name} onClick={()=>s.setViewport(id)}><Icon size={16}/></button>)}</div></div>
    <div className="builder-workspace">{s.mode==="edit"&&<div className={`library-container ${libraryOpen?"mobile-open":""}`}><button className="close-library icon-button" aria-label="关闭组件库" onClick={()=>setLibraryOpen(false)}><X size={16}/></button><Library/></div>}{s.mode==="code"?<CodePanel/>:<Canvas/>}{s.mode==="edit"&&<Inspector/>}</div>
    <footer className="app-footer"><div className="footer-actions"><button onClick={()=>setNewOpen(true)} disabled={!s.ready}><FilePlus2 size={13}/>新建</button><button onClick={()=>fileInput.current?.click()} disabled={!s.ready}><Upload size={13}/>导入 DSL</button><button onClick={()=>{const errors=validateDocument(s.document);s.notify(errors.length?errors.map(e=>`${e.path}: ${e.message}`).join("；"):"校验通过：Schema、组件、Slot、Token 与 Shell 结构有效");}}><ShieldCheck size={13}/>校验</button></div><span className="status-message" role="status" title={s.message}>{s.message||"本地优先 · 页面由 DSL 驱动"}</span><button className="footer-help" onClick={()=>setHelpOpen(true)}>快捷键与说明</button><span className="revision">rev {s.revision}</span></footer>
    {s.loadError&&<div className="recovery-banner" role="alert"><ShieldCheck size={20}/><div><strong>草稿无法恢复，原始数据未覆盖</strong><p>{s.message}</p><p>可导入兼容 DSL，或明确新建页面后再保存。请先通过浏览器存储工具备份原草稿。</p></div></div>}
    {!s.ready&&<div className="loading-screen" role="status"><Layers3 size={28}/><p>正在打开本地工作空间…</p></div>}
  </div><DragOverlay dropAnimation={null}><div className="drag-overlay"><Layers3 size={16}/>{sourceNode?registry[sourceNode.componentRef]?.name:"组件"}</div></DragOverlay>
  <input hidden type="file" ref={fileInput} accept=".json,application/json" aria-label="导入 Page DSL 文件" onChange={async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{if(file.size>2_000_000)throw new Error("文件超过 2 MB 限制");const document=JSON.parse(await file.text());const errors=validateDocument(document);if(errors.length)throw new Error(errors.map(e=>`${e.path}: ${e.message}`).join("；"));setPendingImport(document);}catch(error){s.notify(`导入失败，当前页面未改变：${error instanceof Error?error.message:"无效 JSON"}`);}}}/>
  <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent><DialogTitle>创建空白页面</DialogTitle><DialogDescription>首期仅保存一个当前草稿。新建会替换画布；保存后会覆盖本地草稿。需要保留时，请先导出 DSL。</DialogDescription><DialogFooter><Button variant="outline" onClick={()=>setNewOpen(false)}>取消</Button><Button onClick={()=>{s.newPage();setTarget(null);setNewOpen(false);}}>创建页面</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!pendingImport} onOpenChange={open=>{if(!open)setPendingImport(null);}}><DialogContent><DialogTitle>导入页面</DialogTitle><DialogDescription>将用「{pendingImport?.name}」替换当前画布及撤销历史。原草稿在点击保存前不会被覆盖。</DialogDescription><DialogFooter><Button variant="outline" onClick={()=>setPendingImport(null)}>取消</Button><Button onClick={()=>{if(pendingImport)applyImport(pendingImport);}}>确认导入</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={renaming} onOpenChange={setRenaming}><DialogContent><DialogTitle>重命名页面</DialogTitle><DialogDescription>页面名称用于草稿和导出说明。</DialogDescription><label className="inspector-field">页面名称<input maxLength={80} value={pageName} onChange={e=>setPageName(e.target.value)}/></label><DialogFooter><Button onClick={()=>{if(s.dispatch({type:"page.rename",name:pageName}))setRenaming(false);}}>保存名称</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent><DialogTitle>让页面装配更简单</DialogTitle><DialogDescription>拖动组件卡片右上角的手柄到画布插入线；也可以选择容器后点击组件添加。</DialogDescription><div className="help-list"><p><kbd>⌘ / Ctrl + Z</kbd>撤销</p><p><kbd>⌘ / Ctrl + Shift + Z</kbd>重做</p><p><kbd>Alt + ↑ / ↓</kbd>同级排序</p><p><kbd>Esc</kbd>清除选择</p><p>设计模式用于编辑；预览模式可搜索、筛选、查看详情。</p><p>示例数据、临时 Design Token。真实 API、AI 修改、多页面管理和 Navigation Shell 尚未接入。</p></div></DialogContent></Dialog>
  </DragDropProvider></EditorContext.Provider>;
}
