"use client";
import { useState } from "react";
import { BusinessFields } from "./business-fields";
import { Box, Check, ChevronDown, Code2, Copy, Fingerprint, LockKeyhole, SlidersHorizontal, Trash2 } from "lucide-react";
import { registry, layoutFields, tokenFields, type Field } from "@/core/registry";
import { useBuilder } from "@/core/store";
import { locate } from "@/core/validation";
import { componentIcons } from "./library";
import type { Layout, PageNode } from "@/core/schema";
function FieldEditor({field,value,onCommit}:{field:Field;value:unknown;onCommit:(value:string)=>boolean}){const [draft,setDraft]=useState(String(value??""));const id=`field-${field.key}`;
  function commit(){if(draft!==String(value??"")&&!onCommit(draft))setDraft(String(value??""));}
  return <label className="inspector-field" htmlFor={id}><span>{field.label}</span>{field.type==="select"?<select id={id} value={String(value??"")} onChange={e=>onCommit(e.target.value)}><option value="">继承默认</option>{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select>:field.type==="textarea"?<textarea id={id} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} rows={3} maxLength={1000}/>:<input id={id} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();if(e.key==="Escape"){setDraft(String(value??""));}}} maxLength={200}/>}</label>;
}
function NodeInspector({node}:{node:PageNode}){const [tab,setTab]=useState("content");const [breakpoint,setBreakpoint]=useState<"desktop"|"tablet"|"mobile">("desktop");const dispatch=useBuilder(s=>s.dispatch);const def=registry[node.componentRef];const Icon=componentIcons[node.componentRef]??Box;
  function props(key:string,value:string){return dispatch({type:"node.update",nodeId:node.id,value:{props:{...node.props,[key]:value}}});}
  function layout(key:string,value:string|boolean){const old=breakpoint==="desktop"?node.layout:node.responsive[breakpoint]??{};const next={...old,[key]:value};if(value==="")delete next[key as keyof Layout];return dispatch({type:"node.update",nodeId:node.id,value:breakpoint==="desktop"?{layout:next}:{responsive:{...node.responsive,[breakpoint]:next}}});}
  return <><div className="inspector-selected"><span className="selected-icon"><Icon size={20}/></span><div><strong>{def.name}</strong><small>{node.meta.locked?"App Shell · 锁定区域":def.category==="基础"?"shadcn/ui":"Component Registry"}</small></div>{node.meta.locked&&<LockKeyhole size={13}/>}</div><div className="inspector-switch"><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}>内容</button><button className={tab==="layout"?"active":""} onClick={()=>setTab("layout")}>布局</button><button className={tab==="style"?"active":""} onClick={()=>setTab("style")}>样式</button></div><div className="inspector-scroll">
  {tab==="content"&&<section className="inspector-section"><h3>组件属性 <ChevronDown size={12}/></h3>{def.fields.length?def.fields.map(field=><FieldEditor key={`${node.id}-${field.key}-${JSON.stringify(node.props[field.key])}`} field={field} value={node.props[field.key]} onCommit={v=>props(field.key,v)}/>):<p className="inspector-note">此组件无需内容配置，可在布局中调整排列与间距。</p>}{node.componentRef==="composite.data-table"&&<div className="contract-note"><Code2 size={14}/><div><strong>本地示例数据</strong><p>点击资源行 → 打开详情面板</p><small>未连接真实 API</small></div></div>}</section>}
  {tab==="layout"&&(node.meta.locked?<p className="inspector-note padded">Shell 区域布局由规范锁定。</p>:<section className="inspector-section"><h3>响应式布局 <ChevronDown size={12}/></h3><select className="breakpoint-select" aria-label="布局断点" value={breakpoint} onChange={e=>setBreakpoint(e.target.value as typeof breakpoint)}><option value="desktop">默认 · 桌面</option><option value="tablet">平板覆盖</option><option value="mobile">手机覆盖</option></select>{layoutFields.map(field=><FieldEditor key={`${breakpoint}-${field.key}`} field={field} value={(breakpoint==="desktop"?node.layout:node.responsive[breakpoint])?.[field.key as keyof Layout]} onCommit={v=>layout(field.key,v)}/>)}<label className="checkbox-field"><input type="checkbox" checked={!!(breakpoint==="desktop"?node.layout:node.responsive[breakpoint])?.hidden} onChange={e=>layout("hidden",e.target.checked)}/> 在此断点隐藏</label><p className="inspector-note">手机继承平板，平板继承默认设置。</p></section>)}
  {tab==="style"&&(node.meta.locked?<p className="inspector-note padded">Shell 区域样式由规范锁定。</p>:<section className="inspector-section"><h3>Design Token <ChevronDown size={12}/></h3>{tokenFields.map(field=><FieldEditor key={field.key} field={field} value={node.tokens[field.key as keyof typeof node.tokens]} onCommit={v=>{const tokens={...node.tokens,[field.key]:v};if(!v)delete tokens[field.key as keyof typeof tokens];return dispatch({type:"node.update",nodeId:node.id,value:{tokens}});}}/>)}<div className="token-notice"><span className="tiny-dot"/>临时设计基准 · v0.1</div></section>)}
  {tab==="content"&&node.componentRef==="composite.data-table"&&<BusinessFields/>}
  {tab==="layout"&&node.componentRef==="layout.stack"&&<StackSlots node={node}/>}
  <section className="inspector-section node-info"><h3>组件信息</h3><dl><dt>版本</dt><dd>0.1.0</dd><dt>Slot</dt><dd>{Object.keys(node.slots).join(", ")||"无"}</dd><dt>来源</dt><dd>已注册组件</dd></dl><p><Fingerprint size={12}/>{node.id}</p></section></div><div className="inspector-actions"><button disabled={node.meta.locked} onClick={()=>useBuilder.getState().duplicate()}><Copy size={14}/>复制</button><button className="delete-component" disabled={node.meta.locked} onClick={()=>dispatch({type:"node.remove",nodeId:node.id})}><Trash2 size={14}/>删除</button></div></>;
}
function StackSlots({node}:{node:PageNode}){
  const dispatch=useBuilder(s=>s.dispatch);
  const names=Object.keys(node.slots).sort();
  const widths=(node.props.slotWidths??{}) as Record<string,"fill"|"auto">;
  function add(){const name=Array.from({length:5},(_,i)=>`slot-${i+1}`).find(name=>!node.slots[name]);if(name)dispatch({type:"node.update",nodeId:node.id,value:{slots:{...node.slots,[name]:[]},...(names.length===1?{layout:{...node.layout,direction:"row",align:"center"},responsive:{...node.responsive,mobile:{...node.responsive.mobile,direction:"column",align:"stretch"}}}:{})}});}
  function remove(name:string){if(node.slots[name].length)return;const slots={...node.slots},slotWidths={...widths};delete slots[name];delete slotWidths[name];dispatch({type:"node.update",nodeId:node.id,value:{slots,props:{...node.props,slotWidths}}});}
  return <section className="inspector-section"><h3>容器槽位 <button onClick={add} disabled={names.length>=6}>＋ 添加槽位</button></h3><p className="inspector-note">填充槽位等分剩余宽度，自适应槽位按内容占宽。点击画布槽位后添加组件。</p>{names.map((name,index)=><div className="slot-settings" key={name}><label className="inspector-field"><span>槽位 {index+1} · {name}</span><select aria-label={`槽位 ${index+1} 宽度`} value={widths[name]??"fill"} onChange={e=>dispatch({type:"node.update",nodeId:node.id,value:{props:{...node.props,slotWidths:{...widths,[name]:e.target.value}}}})}><option value="fill">填充 / 等宽</option><option value="auto">适应内容</option></select></label>{name!=="children"&&<button aria-label={`删除槽位 ${index+1}`} disabled={!!node.slots[name].length} title={node.slots[name].length?"请先移走槽位内的组件":"删除空槽位"} onClick={()=>remove(name)}>删除</button>}</div>)}</section>;
}
export function Inspector(){const document=useBuilder(s=>s.document);const selectedId=useBuilder(s=>s.selectedId);const node=selectedId?locate(document,selectedId)?.node:null;return <aside className="inspector-panel" aria-label="属性面板"><div className="panel-title"><SlidersHorizontal size={14}/><strong>属性面板</strong><span>Inspector</span></div>{node?<NodeInspector key={node.id} node={node}/>:<div className="inspector-welcome"><div className="inspector-illustration"><div/><Box size={27}/><div/></div><h2>每个细节，都有章可循</h2><p>在画布或结构树中选择组件，<br/>即可编辑内容、布局与样式。</p><div className="page-summary"><span>当前页面</span><strong>{document.name}</strong><dl><dt>页面框架</dt><dd>Contextual</dd><dt>设计规范</dt><dd>临时基准 v0.1</dd><dt>数据来源</dt><dd>本地示例</dd></dl><p><Check size={12}/> 所有更改通过 Command 校验</p></div><div className="keyboard-tip"><kbd>Alt</kbd> + <kbd>↑ ↓</kbd><span>移动选中的组件</span></div></div>}</aside>;}
