"use client";
import { useState } from "react";
import { useDraggable } from "@dnd-kit/react";
import { Box, Component, Layers3, LayoutTemplate, MousePointer2, PanelRight, Search, Square, SquareMousePointer, Table2, TextCursorInput, Text, GripVertical, LockKeyhole, ChevronDown } from "lucide-react";
import { registry, makeNode } from "@/core/registry";
import { useBuilder } from "@/core/store";
import { locate } from "@/core/validation";
import type { PageNode } from "@/core/schema";
import { useEditor } from "./editor-context";
export const componentIcons:Record<string,typeof Box>={"region.workspace":LayoutTemplate,"layout.stack":Layers3,"shadcn.card":Square,"shadcn.button":SquareMousePointer,"shadcn.input":TextCursorInput,"pattern.page-header":Text,"composite.search-bar":Search,"composite.data-table":Table2,"composite.empty-state":Box,"composite.context-panel":PanelRight,"composite.resource-details":Component};
function LibraryItem({componentRef}:{componentRef:string}){const def=registry[componentRef];const Icon=componentIcons[componentRef]??Box;const {ref,handleRef}=useDraggable({id:`library:${componentRef}`,data:{componentRef}});const {target}=useEditor();
  function add(){const s=useBuilder.getState();const selected=s.selectedId?locate(s.document,s.selectedId):undefined;
    const fallback=componentRef==="composite.resource-details"?{parentId:"context",slot:"children",index:s.document.root[1].slots.children.length}:{parentId:"workspace",slot:"children",index:s.document.root[0].slots.children.length};
    const targetChildren=target?locate(s.document,target.parentId)?.node.slots[target.slot]:undefined;
    const validTarget=target&&targetChildren?{...target,index:Math.min(target.index,targetChildren.length)}:null;
    const dest=validTarget??(selected?.node.slots.children?{parentId:selected.node.id,slot:"children",index:selected.node.slots.children.length}:selected?.parent&&selected.slot?{parentId:selected.parent.id,slot:selected.slot,index:selected.index+1}:fallback);
    const node=makeNode(componentRef);if(s.dispatch({type:"node.insert",node,target:dest})){s.select(node.id);s.notify(`已添加 ${def.name}`);}}
  return <div className="library-item" ref={ref}><button className="library-add" aria-label={`添加 ${def.name}`} title={def.description} onClick={add}><span className="library-icon"><Icon size={20} strokeWidth={1.5}/></span><span>{def.name}</span></button><button ref={handleRef} className="library-drag" aria-label={`从组件库拖动 ${def.name}`}><GripVertical size={12}/></button></div>;
}
function TreeNode({node,depth=0}:{node:PageNode;depth?:number}){const selected=useBuilder(s=>s.selectedId===node.id);const select=useBuilder(s=>s.select);const Icon=componentIcons[node.componentRef]??Box;return <><button className={`tree-node ${selected?"active":""}`} style={{paddingLeft:12+depth*15}} onClick={()=>select(node.id)} aria-label={`在结构树选择 ${registry[node.componentRef]?.name}`}><Icon size={13}/><span>{registry[node.componentRef]?.name??node.componentRef}</span>{node.meta.locked&&<LockKeyhole size={10}/>}</button>{Object.values(node.slots).flat().map(n=><TreeNode key={n.id} node={n} depth={depth+1}/>)}</>;}
export function Library(){const [query,setQuery]=useState("");const [tab,setTab]=useState("components");const document=useBuilder(s=>s.document);return <aside className="library-panel" aria-label="组件库"><div className="panel-tabs"><button className={tab==="components"?"active":""} onClick={()=>setTab("components")}><Component size={14}/>组件</button><button className={tab==="structure"?"active":""} onClick={()=>setTab("structure")}><Layers3 size={14}/>结构</button></div>{tab==="components"?<><div className="library-search"><Search size={14}/><input placeholder="搜索组件…" aria-label="搜索组件" value={query} onChange={e=>setQuery(e.target.value)}/><span>⌕</span></div><div className="library-scroll">{["布局","基础","业务"].map(category=>{const entries=Object.entries(registry).filter(([,d])=>!d.internal&&d.category===category&&`${d.name}${d.description}`.toLowerCase().includes(query.toLowerCase()));return entries.length?<section className="library-group" key={category}><h3><ChevronDown size={12}/>{category}<span>{entries.length}</span></h3><div className="library-grid">{entries.map(([id])=><LibraryItem key={id} componentRef={id}/>)}</div></section>:null;})}{!Object.values(registry).some(d=>!d.internal&&`${d.name}${d.description}`.toLowerCase().includes(query.toLowerCase()))&&<p className="library-no-results">没有匹配的组件</p>}</div><div className="library-help"><MousePointer2 size={15}/><p>拖到画布，开始装配。<br/><span>也可先选择容器，再点击组件添加。</span></p></div></>:<div className="structure-tree"><div className="tree-root"><LayoutTemplate size={14}/>{document.name}</div>{document.root.map(node=><TreeNode node={node} key={node.id}/>)}<div className="tree-tip"><LockKeyhole size={13}/> Shell 区域已锁定</div></div>}<div className="library-footer"><span><span className="tiny-dot"/>本地组件注册表</span><span>v0.1</span></div></aside>;}
