"use client";
import { createContext, useContext, useEffect, useId, useRef, useState, type ReactNode } from "react";
import { Box, ChevronRight, FileText, LayoutGrid, Layers3, Plug, Search, Sparkles, X, ArrowUpRight, CircleHelp, PanelLeftClose, PanelLeftOpen, Check, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { resources, type Resource } from "./data";
import { presentation, type Presentation } from "./presentation";

type Runtime={query:string;setQuery:(q:string)=>void;filter:string;setFilter:(f:string)=>void;selected:Resource|null;select:(r:Resource|null)=>void;notice:string;notify:(s:string)=>void};
const Context=createContext<Runtime|null>(null);
export function useRuntime(){const value=useContext(Context);if(!value)throw new Error("RuntimeProvider is required");return value;}
export function RuntimeProvider({children}:{children:ReactNode}){const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [selected,select]=useState<Resource|null>(null);const [notice,notify]=useState("");return <Context.Provider value={{query,setQuery,filter,setFilter,selected,select,notice,notify}}>{children}</Context.Provider>;}
export function ContextualShell({workspaceName,children}:{workspaceName:string;children:ReactNode}){
  const {notice,notify}=useRuntime();const [collapsed,setCollapsed]=useState(false);
  return <div className="page-surface"><div className={`runtime-shell ${collapsed?"nav-collapsed":""}`}>
    <aside className="runtime-sidebar" aria-label="工作空间导航">
      <div className="workspace-brand"><span className="workspace-mark"><Layers3 size={19}/></span><span className="nav-label"><strong>{workspaceName}</strong><small>团队工作空间</small></span></div>
      <span className="sidebar-caption nav-label">工作空间</span>
      <button className="runtime-nav active" aria-current="page" onClick={()=>notify("当前页面：资源中心")}><LayoutGrid size={17}/><span className="nav-label">资源中心</span><span className="nav-count nav-label">{resources.length}</span></button>
      <div className="sidebar-note nav-label"><span className="tiny-dot"/> 本地示例空间<p>可预览搜索、筛选和详情。所有资源均为示例数据。</p></div>
      <div className="sidebar-bottom"><button className="runtime-nav" onClick={()=>notify("通过搜索查找资源，点击资源名称查看详情。")}><CircleHelp size={17}/><span className="nav-label">使用帮助</span></button><button className="runtime-nav collapse-nav" aria-label={collapsed?"展开导航":"折叠导航"} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}<span className="nav-label">折叠导航</span></button><div className="profile"><span className="avatar">JD</span><span className="nav-label"><strong>Jamie Davis</strong><small>个人工作空间</small></span></div></div>
    </aside><div className="runtime-body"><div className="runtime-topbar"><span>工作空间</span><ChevronRight size={13}/><strong>资源中心</strong><span className="example-label">示例数据</span></div><div className="runtime-columns">{children}</div><div className="runtime-notice" role="status">{notice&&<><Check size={14}/>{notice}<button aria-label="关闭提示" onClick={()=>notify("")}><X size={13}/></button></>}</div></div>
  </div></div>;
}
type BlockProps=Presentation&{children?:ReactNode};
export function WorkspacePane({children}:BlockProps){return <main className="workspace-pane" aria-label="页面内容">{children}</main>;}
export function StackSlot({name,width="fill",children}:{name:string;width?:"fill"|"auto";children?:ReactNode}){return <div className={`stack-slot stack-slot-${width}`} data-slot={name}>{children}</div>;}
export function Stack({children,...config}:BlockProps & {slotWidths?:Record<string,"fill"|"auto">}){return <div {...presentation(config)} data-component="layout.stack">{children}</div>;}
export function CardBlock({title,children,...config}:BlockProps&{title:string}){return <div {...presentation(config)}><Card className="runtime-card">{title&&<CardHeader><CardTitle>{title}</CardTitle></CardHeader>}<CardContent className="card-slot">{children}</CardContent></Card></div>;}
export function ButtonBlock({text,variant,message,...config}:BlockProps&{text:string;variant:"default"|"outline"|"secondary";message:string}){const {notify}=useRuntime();return <div {...presentation(config)}><Button variant={variant} className="runtime-button" onClick={()=>notify(message)}>{text}<ArrowUpRight size={14}/></Button></div>;}
export function InputBlock({label,placeholder,...config}:BlockProps&{label:string;placeholder:string}){const id=useId();return <div {...presentation(config)}><label className="runtime-field" htmlFor={id}>{label}<Input id={id} placeholder={placeholder}/></label></div>;}
export function PageHeader({title,description,...config}:BlockProps&{title:string;description:string}){return <div {...presentation(config)}><header className="resource-heading"><span className="page-eyebrow"><Box size={14}/> RESOURCE LIBRARY</span><h1>{title}</h1><p>{description}</p><div className="resource-metrics"><span><b>{resources.length}</b> 全部资源</span><span><i className="tiny-dot"/><b>{resources.filter(r=>r.status==="已发布").length}</b> 已发布</span><span><b>3</b> 资源类型</span></div></header></div>;}
export function SearchBar({placeholder,...config}:BlockProps&{placeholder:string}){const {query,setQuery,filter,setFilter}=useRuntime();return <div {...presentation(config)}><div className="resource-search"><div className="search-input"><Search size={16}/><Input aria-label="搜索资源" value={query} placeholder={placeholder} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除搜索" onClick={()=>setQuery("")}><X size={14}/></button>}</div><label className="resource-filter"><SlidersHorizontal size={14}/><span className="sr-only">资源类型</span><select aria-label="资源类型" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部类型</option><option>Skill</option><option>MCP</option><option>Document</option></select></label></div></div>;}
export function ResourceIcon({type}:{type:Resource["type"]}){const Icon=type==="Skill"?Sparkles:type==="MCP"?Plug:FileText;return <span className={`resource-icon ${type.toLowerCase()}`}><Icon size={17}/></span>;}
export function DataTable({density,openDetails=true,...config}:BlockProps&{density:"comfortable"|"compact";openDetails?:boolean}){const {query,filter,select,selected}=useRuntime();const filtered=resources.filter(r=>(filter==="all"||r.type===filter)&&`${r.name} ${r.description}`.toLowerCase().includes(query.toLowerCase()));return <div {...presentation(config)}><div className={`table-card ${density}`}><div className="table-scroll"><table><caption className="sr-only">资源列表</caption><thead><tr><th>资源名称</th><th>类型</th><th>状态</th><th>更新时间</th><th><span className="sr-only">详情</span></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} data-selected={selected?.id===r.id}><td><div className="resource-name"><ResourceIcon type={r.type}/><div>{openDetails?<button onClick={()=>select(r)}>{r.name}</button>:<strong>{r.name}</strong>}<p>{r.description}</p></div></div></td><td><span className="type-badge">{r.type}</span></td><td><span className={`status-badge ${r.status==="草稿"?"draft":""}`}><i/>{r.status}</span></td><td className="date-cell">{r.updated}</td><td>{openDetails&&<button aria-label={`查看 ${r.name}`} className="row-more" onClick={()=>select(r)}><ChevronRight size={16}/></button>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="table-empty"><Search size={24}/><strong>没有找到匹配资源</strong><span>试试其他关键词或资源类型</span></div>}</div><div className="table-footer"><span>显示 {filtered.length} / {resources.length} 条资源</span><span>点击资源查看详情 <ArrowUpRight size={12}/></span></div></div></div>;}
export function EmptyState({title,description,...config}:BlockProps&{title:string;description:string}){return <div {...presentation(config)}><div className="empty-state"><Box size={26}/><h2>{title}</h2><p>{description}</p></div></div>;}
export function ContextPanel({title,children,editing=false}:BlockProps&{title:string;editing?:boolean}){const {selected,select}=useRuntime();const ref=useRef<HTMLElement>(null);const [narrow,setNarrow]=useState(false);useEffect(()=>{const element=ref.current?.closest(".page-surface");if(!element)return;const observer=new ResizeObserver(([entry])=>setNarrow(entry.contentRect.width<=1100));observer.observe(element);return ()=>observer.disconnect();},[]);return <><aside ref={ref} className={`context-panel ${selected?"is-open":""}`} aria-label={title}><div className="context-heading"><strong>{title}</strong>{selected&&<button aria-label="关闭详情" onClick={()=>select(null)}><X size={16}/></button>}</div>{selected||editing?children:<div className="context-placeholder"><Box size={28}/><strong>查看资源详情</strong><p>选择一条资源，了解更多信息。</p></div>}</aside><div className="mobile-context"><Dialog open={!!selected&&narrow&&!editing} onOpenChange={open=>{if(!open)select(null);}}><DialogContent className="runtime-detail-dialog"><DialogTitle>{title}</DialogTitle><DialogDescription>当前所选资源的示例信息</DialogDescription>{children}</DialogContent></Dialog></div></>;}
export function ResourceDetails(config:BlockProps){const {selected}=useRuntime();if(!selected)return <div className="context-placeholder">选择资源后显示详情</div>;return <div {...presentation(config)}><article className="resource-details"><ResourceIcon type={selected.type}/><h2>{selected.name}</h2><span className="type-badge">{selected.type}</span><p>{selected.description}</p><dl><dt>发布状态</dt><dd>{selected.status}</dd><dt>当前版本</dt><dd>v{selected.version}</dd><dt>维护团队</dt><dd>{selected.author}</dd><dt>最近更新</dt><dd>{selected.updated}</dd></dl><div className="detail-note"><Check size={14}/><span>此资源来自本地示例数据，可用于验证页面交互。</span></div></article></div>;}
