"use client";
import { Children, createContext, isValidElement, useContext, useEffect, useId, useRef, useState, type ReactNode } from "react";
import { Box, ChevronRight, FileText, LayoutGrid, Layers3, Plug, Search, Sparkles, X, ArrowUpRight, CircleHelp, PanelLeftClose, PanelLeftOpen, Check, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { resources, resourceListDetail, displayValue, filterRows, type Resource, type DataRecord, type ListDetail, type RecordAction } from "./data";
import { createRecordSession, fieldError, type RecordIssue, type RecordResult } from "./records";
import { presentation, type Presentation } from "./presentation";

type FormState={action:RecordAction;record?:DataRecord;returnFocus:HTMLElement|null};
type Submit=(request:unknown)=>Promise<RecordResult>;
/** Optional persistent data source (e.g. SQLite API); without it records live in an isolated session simulation. */
export type RecordAdapter={submit:Submit;label:string};
/** Optional app navigation for multi-page prototypes; detailHref may contain {id}. */
export type Navigation={items:{label:string;href:string;count?:number;active?:boolean}[];links?:{label:string;href:string}[];detailHref?:string};
type Runtime={openForm:(action:RecordAction,record?:DataRecord)=>void;config:ListDetail;legacy:boolean;pageTitle:string;query:string;setQuery:(q:string)=>void;filters:Record<string,string>;setFilters:(f:Record<string,string>)=>void;selected:DataRecord|null;select:(r:DataRecord|null)=>void;notice:string;notify:(s:string)=>void;adapter?:RecordAdapter;navigation?:Navigation};
const Context=createContext<Runtime|null>(null);
export function useRuntime(){const value=useContext(Context);if(!value)throw new Error("RuntimeProvider is required");return value;}
export function RuntimeProvider({children,listDetail,pageTitle="资源中心",adapter,navigation,initialSelectedId=null}:{children:ReactNode;listDetail?:ListDetail;pageTitle?:string;adapter?:RecordAdapter;navigation?:Navigation;initialSelectedId?:string|null}){
  const base=listDetail??resourceListDetail;
  const [session]=useState(()=>createRecordSession(base));const [rows,setRows]=useState(()=>adapter?base.rows:session.rows);
  const submit:Submit=adapter?.submit??session.submit;
  const [query,setQuery]=useState("");const [filters,setFilters]=useState<Record<string,string>>({});
  const [selectedId,setSelectedId]=useState<string|null>(initialSelectedId);const [notice,notify]=useState("");const [form,setForm]=useState<FormState|null>(null);
  const config={...base,rows},selected=rows.find(row=>row.id===selectedId)??null;
  const select=(row:DataRecord|null)=>setSelectedId(row?.id??null);
  const openForm=(action:RecordAction,record?:DataRecord)=>{if(base.form?.actions.includes(action))setForm({action,record,returnFocus:document.activeElement instanceof HTMLElement?document.activeElement:null});};
  return <Context.Provider value={{config,legacy:!listDetail,pageTitle:listDetail?pageTitle:"资源中心",query,setQuery,filters,setFilters,selected,select,notice,notify,openForm,adapter,navigation}}>{children}{form&&<BusinessForm config={config} state={form} persistent={adapter?.label} close={()=>setForm(null)} submit={submit} success={(record,next)=>{setRows(next);if(form.action==="record.create")select(record);notify(adapter?`${form.action==="record.create"?"新增":"编辑"}成功：${record[config.titleField]}，已保存到${adapter.label}。`:`模拟${form.action==="record.create"?"新增":"编辑"}成功：${record[config.titleField]}。刷新后恢复示例数据。`);setForm(null);}}/>}</Context.Provider>;
}
export function ContextualShell({workspaceName,children}:{workspaceName:string;children:ReactNode}){
  const {notice,notify,config,legacy,pageTitle,adapter,navigation}=useRuntime();const [collapsed,setCollapsed]=useState(false);
  return <div className="page-surface"><div className={`runtime-shell ${collapsed?"nav-collapsed":""}`}>
    <aside className="runtime-sidebar" aria-label="工作空间导航">
      <div className="workspace-brand"><span className="workspace-mark"><Layers3 size={19}/></span><span className="nav-label"><strong>{workspaceName}</strong><small>团队工作空间</small></span></div>
      <span className="sidebar-caption nav-label">工作空间</span>
      {navigation?navigation.items.map(item=><a key={item.href} className={`runtime-nav ${item.active?"active":""}`} aria-current={item.active?"page":undefined} href={item.href}><LayoutGrid size={17}/><span className="nav-label">{item.label}</span>{item.count!==undefined&&<span className="nav-count nav-label">{item.count}</span>}</a>)
        :<button className="runtime-nav active" aria-current="page" onClick={()=>notify(`当前页面：${pageTitle}`)}><LayoutGrid size={17}/><span className="nav-label">{pageTitle}</span><span className="nav-count nav-label">{config.rows.length}</span></button>}
      {adapter?<div className="sidebar-note nav-label"><span className="tiny-dot"/> 原型数据<p>{config.entityName}数据保存在{adapter.label}，新增与编辑会持久化。</p></div>:<div className="sidebar-note nav-label"><span className="tiny-dot"/> 本地示例空间<p>可预览搜索、筛选和详情。所有{config.entityName}均为示例数据。</p></div>}
      <div className="sidebar-bottom">{navigation?.links?.map(link=><a key={link.href} className="runtime-nav" href={link.href}><ArrowUpRight size={17}/><span className="nav-label">{link.label}</span></a>)}<button className="runtime-nav" onClick={()=>notify(`通过搜索查找${config.entityName}，点击名称查看详情。`)}><CircleHelp size={17}/><span className="nav-label">使用帮助</span></button><button className="runtime-nav collapse-nav" aria-label={collapsed?"展开导航":"折叠导航"} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}<span className="nav-label">折叠导航</span></button><div className="profile"><span className="avatar">JD</span><span className="nav-label"><strong>Jamie Davis</strong><small>个人工作空间</small></span></div></div>
    </aside><div className="runtime-body"><div className="runtime-topbar"><span>工作空间</span><ChevronRight size={13}/><strong>{pageTitle}</strong><span className="example-label">{adapter?adapter.label:legacy?"示例数据":"SIMULATION 示例数据"}</span></div><div className="runtime-columns">{children}</div><div className="runtime-notice" role="status">{notice&&<><Check size={14}/>{notice}<button aria-label="关闭提示" onClick={()=>notify("")}><X size={13}/></button></>}</div></div>
  </div></div>;
}
type BlockProps=Presentation&{children?:ReactNode;slots?:Record<string,ReactNode>};
export function WorkspacePane({children,slots}:BlockProps){return <main className="workspace-pane" aria-label="页面内容">{slots?.children??children}</main>;}
export function StackSlot({name,width="fill",children}:{name:string;width?:"fill"|"auto";children?:ReactNode}){return <div className={`stack-slot stack-slot-${width}`} data-slot={name}>{children}</div>;}
export function Stack({children,slots,slotWidths,...config}:BlockProps & {slotWidths?:Record<string,"fill"|"auto">}){const names=Object.keys(slots??{}).sort();return <div {...presentation(config)} data-component="layout.stack">{names.length>1?names.map(name=><StackSlot key={name} name={name} width={slotWidths?.[name]}>{slots![name]}</StackSlot>):slots?.children??children}</div>;}
export function CardBlock({title,children,slots,...config}:BlockProps&{title:string}){return <div {...presentation(config)}><Card className="runtime-card">{title&&<CardHeader><CardTitle>{title}</CardTitle></CardHeader>}<CardContent className="card-slot">{slots?.children??children}</CardContent></Card></div>;}
export function ButtonBlock({text,variant,message,...config}:BlockProps&{text:string;variant:"default"|"outline"|"secondary";message:string}){const {notify}=useRuntime();return <div {...presentation(config)}><Button variant={variant} className="runtime-button" onClick={()=>notify(message)}>{text}<ArrowUpRight size={14}/></Button></div>;}
export function BadgeBlock({text,variant,...config}:BlockProps&{text:string;variant:"default"|"secondary"|"outline"|"destructive"}){return <div {...presentation(config)}><Badge variant={variant} className="runtime-badge">{text}</Badge></div>;}
export function TabsSlot({name,children}:{name:string;children?:ReactNode}){return <div className="tabs-slot" data-slot={name}>{children}</div>;}
function slotChildren(children:ReactNode){const map=new Map<string,ReactNode>();Children.forEach(children,child=>{if(isValidElement<{name?:string;children?:ReactNode}>(child)&&child.type===TabsSlot&&child.props.name)map.set(child.props.name,child.props.children);});return map;}
export function TabsBlock({label1,label2,label3,editing=false,children,slots:namedSlots,...config}:BlockProps&{label1:string;label2:string;label3:string;editing?:boolean}){const slots=namedSlots??Object.fromEntries(slotChildren(children));const tabs=[["tab-1",label1],["tab-2",label2],["tab-3",label3]].filter(([,label])=>label);
  if(editing)return <div {...presentation(config)}><div className="runtime-tabs editing">{tabs.map(([key,label])=><section key={key} className="tabs-edit-panel" aria-label={label}><header>{label}</header><div className="tabs-panel-body">{slots[key]}</div></section>)}</div></div>;
  return <div {...presentation(config)}><Tabs defaultValue={tabs[0]?.[0]} className="runtime-tabs"><TabsList>{tabs.map(([key,label])=><TabsTrigger key={key} value={key}>{label}</TabsTrigger>)}</TabsList>{tabs.map(([key])=><TabsContent key={key} value={key} className="tabs-panel-body">{slots[key]}</TabsContent>)}</Tabs></div>;}
export function InputBlock({label,placeholder,...config}:BlockProps&{label:string;placeholder:string}){const id=useId();return <div {...presentation(config)}><label className="runtime-field" htmlFor={id}>{label}<Input id={id} placeholder={placeholder}/></label></div>;}
export function PageHeader({title,description,...presentationConfig}:BlockProps&{title:string;description:string}){const {config,legacy,openForm,adapter}=useRuntime();return <div {...presentation(presentationConfig)}><header className="resource-heading"><span className="page-eyebrow"><Box size={14}/> {adapter?adapter.label:legacy?"RESOURCE LIBRARY":"SIMULATION 示例数据"}</span><h1>{title}</h1><p>{description}</p><div className="resource-metrics"><span><b>{config.rows.length}</b> 全部{config.entityName}</span>{legacy&&<><span><i className="tiny-dot"/><b>{resources.filter(r=>r.status==="已发布").length}</b> 已发布</span><span><b>3</b> 资源类型</span></>}</div>{config.form?.actions.includes("record.create")&&<Button className="record-create" onClick={()=>openForm("record.create")}>新增{config.entityName}</Button>}</header></div>;}
export function SearchBar({placeholder,...presentationConfig}:BlockProps&{placeholder:string}){const {config,legacy,query,setQuery,filters,setFilters}=useRuntime();return <div {...presentation(presentationConfig)}><div className="resource-search"><div className="search-input"><Search size={16}/><Input aria-label={`搜索${config.entityName}`} value={query} placeholder={placeholder} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除搜索" onClick={()=>setQuery("")}><X size={14}/></button>}</div>{config.filters.map(key=>{const field=config.fields.find(f=>f.key===key)!;const values=legacy?["Skill","MCP","Document"]:[...new Set(config.rows.map(row=>String(row[key])))];return <label className="resource-filter" key={key}><SlidersHorizontal size={14}/><span className="sr-only">{field.label}</span><select aria-label={field.label} value={filters[key]===undefined?"all":legacy?filters[key]:`value:${filters[key]}`} onChange={e=>{const next={...filters};if(e.target.value==="all")delete next[key];else next[key]=legacy?e.target.value:e.target.value.slice(6);setFilters(next);}}><option value="all">{legacy?"全部类型":`全部${field.label}`}</option>{values.map(value=><option key={value} value={legacy?value:`value:${value}`}>{displayValue(config,key,config.rows.find(row=>String(row[key])===value)![key])}</option>)}</select></label>;})}</div></div>;}
export function ResourceIcon({type}:{type:Resource["type"]}){const Icon=type==="Skill"?Sparkles:type==="MCP"?Plug:FileText;return <span className={`resource-icon ${type.toLowerCase()}`}><Icon size={17}/></span>;}
export function DataTable({density,openDetails=true,...presentationConfig}:BlockProps&{density:"comfortable"|"compact";openDetails?:boolean}){const {config,legacy,query,filters,select,selected}=useRuntime();const filtered=filterRows(config,query,filters);return <div {...presentation(presentationConfig)}><div className={`table-card ${density}`}><div className="table-scroll"><table><caption className="sr-only">{config.entityName}列表</caption><thead><tr>{config.columns.map(column=><th key={column.field}>{column.title}</th>)}<th><span className="sr-only">详情</span></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} data-selected={selected?.id===row.id}>{config.columns.map(column=><td key={column.field} className={legacy&&column.field==="updated"?"date-cell":undefined}>{column.field===config.titleField?<div className="resource-name">{legacy&&<ResourceIcon type={row.type as Resource["type"]}/>}<div>{openDetails?<button onClick={()=>select(row)}>{displayValue(config,column.field,row[column.field])}</button>:<strong>{displayValue(config,column.field,row[column.field])}</strong>}{config.descriptionField&&<p>{String(row[config.descriptionField])}</p>}</div></div>:legacy&&column.field==="type"?<span className="type-badge">{String(row.type)}</span>:legacy&&column.field==="status"?<span className={`status-badge ${row.status==="草稿"?"draft":""}`}><i/>{String(row.status)}</span>:displayValue(config,column.field,row[column.field])}</td>)}<td>{openDetails&&<button aria-label={`查看 ${row[config.titleField]}`} className="row-more" onClick={()=>select(row)}><ChevronRight size={16}/></button>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="table-empty"><Search size={24}/><strong>没有找到匹配{config.entityName}</strong><span>{legacy?"试试其他关键词或资源类型":"试试其他关键词或筛选条件"}</span></div>}</div><div className="table-footer"><span>显示 {filtered.length} / {config.rows.length} 条{config.entityName}</span><span>点击{config.entityName}查看详情 <ArrowUpRight size={12}/></span></div></div></div>;}
export function EmptyState({title,description,...config}:BlockProps&{title:string;description:string}){return <div {...presentation(config)}><div className="empty-state"><Box size={26}/><h2>{title}</h2><p>{description}</p></div></div>;}
export function ContextPanel({title,children,slots,editing=false}:BlockProps&{title:string;editing?:boolean}){const content=slots?.children??children;const {selected,select,config,adapter}=useRuntime();const ref=useRef<HTMLElement>(null);const [narrow,setNarrow]=useState(false);useEffect(()=>{const element=ref.current?.closest(".page-surface");if(!element)return;const observer=new ResizeObserver(([entry])=>setNarrow(entry.contentRect.width<=1100));observer.observe(element);return ()=>observer.disconnect();},[]);return <><aside ref={ref} className={`context-panel ${selected?"is-open":""}`} aria-label={title}><div className="context-heading"><strong>{title}</strong>{selected&&<button aria-label="关闭详情" onClick={()=>select(null)}><X size={16}/></button>}</div>{selected||editing?content:<div className="context-placeholder"><Box size={28}/><strong>查看{config.entityName}详情</strong><p>选择一条{config.entityName}，了解更多信息。</p></div>}</aside><div className="mobile-context"><Dialog open={!!selected&&narrow&&!editing} onOpenChange={open=>{if(!open)select(null);}}><DialogContent className="runtime-detail-dialog"><DialogTitle>{title}</DialogTitle><DialogDescription>{adapter?`当前所选${config.entityName}的信息`:`当前所选${config.entityName}的示例信息`}</DialogDescription>{content}</DialogContent></Dialog></div></>;}
export function ResourceDetails(presentationConfig:BlockProps){const {selected,config,legacy,openForm,adapter,navigation}=useRuntime();if(!selected)return <div className="context-placeholder">选择{config.entityName}后显示详情</div>;return <div {...presentation(presentationConfig)}><article className="resource-details">{legacy&&<ResourceIcon type={selected.type as Resource["type"]}/>}<h2>{displayValue(config,config.titleField,selected[config.titleField])}</h2>{legacy&&<span className="type-badge">{String(selected.type)}</span>}{config.descriptionField&&<p>{String(selected[config.descriptionField])}</p>}<dl>{config.detailFields.map(key=><DetailField key={key} label={config.fields.find(field=>field.key===key)!.label} value={(legacy&&key==="version"?"v":"")+displayValue(config,key,selected[key])}/>)}</dl>{config.form?.actions.includes("record.update")&&<Button variant="outline" className="record-edit" onClick={()=>openForm("record.update",selected)}>编辑{config.entityName}</Button>}{navigation?.detailHref&&<Button asChild variant="ghost" className="record-open"><a href={navigation.detailHref.replace("{id}",encodeURIComponent(selected.id))}>打开详情页<ArrowUpRight size={14}/></a></Button>}<div className="detail-note"><Check size={14}/><span>{adapter?`数据来自${adapter.label}。`:legacy?"此资源来自本地示例数据，可用于验证页面交互。":config.form?"SIMULATION 会话内模拟操作，刷新恢复示例数据。":"SIMULATION 示例数据，仅用于验证页面交互。"}</span></div></article></div>;}
function DetailField({label,value}:{label:string;value:string}){return <><dt>{label}</dt><dd>{value}</dd></>;}

type FieldInput=React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>;
/** Shared create/edit form state: defaults or record values, client validation, submit lock, server feedback. */
export function useRecordForm({config,action,record,submit,success}:{config:ListDetail;action:RecordAction;record?:DataRecord;submit:Submit;success:(record:DataRecord,rows:DataRecord[])=>void}){
  const id=useId(),formRef=useRef<HTMLFormElement>(null),busy=useRef(false);
  const fields=config.form!.fields.map(key=>config.fields.find(field=>field.key===key)!);
  const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(field=>[field.key,String(record?.[field.key]??field.default??"")])));
  const [errors,setErrors]=useState<RecordIssue[]>([]),[message,setMessage]=useState(""),[pending,setPending]=useState(false);
  const focusError=(issues:RecordIssue[])=>{const key=issues[0]?.path.split(".").at(-1);formRef.current?.querySelector<HTMLElement>(`[name="${fields.find(field=>field.key===key)?.key??fields[0].key}"]`)?.focus();};
  async function save(){
    if(busy.current)return;
    const input=Object.fromEntries(fields.map(field=>{const raw=values[field.key];return [field.key,field.options?field.options.find(option=>String(option.value)===raw)?.value:field.type==="number"?(raw.trim()===""?undefined:Number(raw)):raw];}));
    const issues=fields.flatMap(field=>{const error=fieldError(field,input[field.key]);return error?[{path:`values.${field.key}`,message:error}]:[];});
    setErrors(issues);setMessage("");if(issues.length){focusError(issues);return;}
    busy.current=true;setPending(true);
    try{
      const result=await submit({operationId:crypto.randomUUID(),action,...(record?{recordId:record.id}:{}),values:input});
      if(result.ok)success(result.record,result.rows);else{setErrors(result.errors);setMessage(result.message);focusError(result.errors);}
    }catch{setMessage("提交失败，输入已保留，请重试。");}
    finally{busy.current=false;setPending(false);}
  }
  return {id,formRef,busy,fields,values,setValue:(key:string,value:string)=>setValues(current=>({...current,[key]:value})),errors,message,pending,save};
}
export function RecordFormBody({form,close,pendingText}:{form:ReturnType<typeof useRecordForm>;close:()=>void;pendingText:string}){
  const {id,formRef,fields,values,setValue,errors,message,pending,save}=form;
  return <form ref={formRef} noValidate aria-busy={pending} onSubmit={event=>{event.preventDefault();void save();}}>
    {fields.map(field=>{const error=errors.find(issue=>issue.path===`values.${field.key}`)?.message,errorId=`${id}-${field.key}-error`,fieldId=`${id}-${field.key}`;
      const props={id:fieldId,name:field.key,value:values[field.key],disabled:pending,required:field.required,"aria-invalid":!!error,"aria-describedby":error?errorId:undefined,onChange:(event:FieldInput)=>setValue(field.key,event.target.value)};
      return <div className="record-form-field" key={field.key}><label htmlFor={fieldId}>{field.label}{field.required&&<span aria-hidden="true"> *</span>}</label>{field.options?<select {...props}><option value="">请选择{field.label}</option>{field.options.map(option=><option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</select>:field.format==="textarea"?<textarea {...props} className="record-textarea" rows={4} maxLength={field.maxLength}/>:<Input {...props} type={field.type==="number"?"number":field.format==="date"?"date":"text"} minLength={field.minLength} maxLength={field.maxLength} min={field.min} max={field.max} step={field.integer?1:"any"}/>}{error&&<p id={errorId} className="record-field-error" role="alert">{error}</p>}</div>;
    })}
    <p className="record-form-message" role={message?"alert":"status"} aria-live="polite">{pending?pendingText:message}</p>
    <div className="record-form-actions"><Button type="button" variant="outline" disabled={pending} onClick={close}>取消</Button><Button type="submit" disabled={pending}>{pending?"提交中…":"保存记录"}</Button></div>
  </form>;
}
export function BusinessForm({config,state,close,submit,success,persistent}:{config:ListDetail;state:FormState;close:()=>void;submit:Submit;success:(record:DataRecord,rows:DataRecord[])=>void;persistent?:string}){
  const form=useRecordForm({config,action:state.action,record:state.record,submit,success});const {formRef,busy,pending}=form;
  const title=`${state.action==="record.create"?"新增":"编辑"}${config.entityName}`;
  return <Dialog open onOpenChange={open=>{if(!open&&!busy.current)close();}}><DialogContent className="runtime-detail-dialog runtime-form-dialog" showCloseButton={false} onOpenAutoFocus={event=>{event.preventDefault();formRef.current?.querySelector<HTMLElement>("input,select,textarea")?.focus();}} onEscapeKeyDown={event=>{if(busy.current)event.preventDefault();}} onInteractOutside={event=>{if(busy.current)event.preventDefault();}} onCloseAutoFocus={event=>{event.preventDefault();state.returnFocus?.focus();}}>
    <DialogTitle>{title}</DialogTitle><DialogDescription>{persistent?`保存后写入${persistent}。`:"SIMULATION 会话内模拟操作，刷新恢复示例数据。"}</DialogDescription>
    <button className="record-form-close" aria-label="关闭表单" disabled={pending} onClick={close}><X size={16}/></button>
    <RecordFormBody form={form} close={close} pendingText={persistent?"正在保存…":"正在模拟提交…"}/>
  </DialogContent></Dialog>;
}
