import { readFile } from "node:fs/promises";
import path from "node:path";
import { generateReact, stableStringify } from "./generator";
import type { PageDocument } from "./schema";
// Export only the runtime closure. No Builder, registry, store, command or drag dependency.
const files=["src/runtime/components.tsx","src/runtime/presentation.ts","src/runtime/tokens.ts","src/runtime/theme.css","src/runtime/data.ts","src/runtime/records.ts","src/runtime/styles.css","src/components/ui/button.tsx","src/components/ui/input.tsx","src/components/ui/card.tsx","src/components/ui/dialog.tsx","src/components/ui/badge.tsx","src/components/ui/tabs.tsx","src/core/utils.ts","postcss.config.mjs",".nvmrc"];
export async function exportProject(document:PageDocument):Promise<Record<string,string>>{
  const root=process.cwd();const pkg=JSON.parse(await readFile(path.join(root,"package.json"),"utf8"));
  const dependencies=Object.fromEntries(["next","react","react-dom","lucide-react","radix-ui","class-variance-authority","clsx","tailwind-merge"].map(name=>[name,pkg.dependencies[name]]));
  const devDependencies=Object.fromEntries(["typescript","@types/node","@types/react","@types/react-dom","tailwindcss","@tailwindcss/postcss"].map(name=>[name,pkg.devDependencies[name]]));
  const result:Record<string,string>={};
  await Promise.all(files.map(async name=>{result[name]=await readFile(path.join(root,name),"utf8");}));
  result["src/app/page.tsx"]=await generateReact(document);
  result["src/app/layout.tsx"]='import "./globals.css";\nexport default function Layout({children}:{children:React.ReactNode}){return <html lang="zh-CN"><body>{children}</body></html>}\n';
  result["src/app/globals.css"]='@import "tailwindcss";\n@import "../runtime/styles.css";\n';
  result["package.json"]=JSON.stringify({name:"composed-page",version:"0.1.0",private:true,engines:{node:"24.x"},scripts:{dev:"next dev --hostname 127.0.0.1 --port 3101",build:"next build",start:"next start --hostname 127.0.0.1 --port 3101",typecheck:"tsc --noEmit"},dependencies,devDependencies},null,2)+"\n";
  const tsconfig=JSON.parse(await readFile(path.join(root,"tsconfig.json"),"utf8"));tsconfig.exclude=["node_modules"];result["tsconfig.json"]=JSON.stringify(tsconfig,null,2)+"\n";
  result["next-env.d.ts"]='/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n';
  result["page.dsl.json"]=stableStringify(document)+"\n";
  result["README.md"]='# '+document.name+'\n\nGenerated by Page Composer 0.1.0. Node 24 required.\n\n```sh\nnpm install\nnpm run build\nnpm start\n```\n\nOpen http://127.0.0.1:3101. This project runs independently of the editor. Data is local fixture data; no real API integration. Design tokens are provisional. Page source is src/app/page.tsx; page.dsl.json is the export source of truth. Changes to exported React are not imported back to the builder. Dependencies are pinned; commit the generated package-lock.json after installation.\n';
  result["THIRD_PARTY.md"]='Existing UI primitives are attributed to shadcn/ui (MIT) by components.json, local source and initial commit a17c443: https://github.com/shadcn-ui/ui. Exact upstream revision, installation history and local differences remain unverified. Other dependency licenses are included in installed packages. Runtime adapters and resource compositions are application code.\n';
  return Object.fromEntries(Object.entries(result).sort(([a],[b])=>a<b?-1:1));
}
