import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';

const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000}});
page.setDefaultTimeout(15000);
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('dialog',dialog=>dialog.accept());
async function downloadDsl(){const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'导出 DSL',exact:true}).first().click();return JSON.parse(await readFile(await (await downloaded).path(),'utf8'));}
try{
  await page.goto(process.env.COMPOSER_URL??'http://127.0.0.1:3100');
  await page.getByRole('button',{name:'保存',exact:true}).waitFor();
  await page.getByRole('button',{name:'添加 Stack',exact:true}).click();
  for(let i=0;i<3;i++)await page.keyboard.press('Alt+ArrowUp');
  const stack=page.getByRole('group',{name:'编辑 Stack',exact:true});
  const id=await stack.getAttribute('data-node-id');
  await page.getByRole('button',{name:'布局',exact:true}).click();
  await page.getByRole('button',{name:'＋ 添加槽位',exact:true}).click();
  await page.getByLabel('槽位 2 宽度').selectOption('auto');
  await stack.getByRole('button',{name:'槽位 1',exact:true}).click();
  await page.getByRole('button',{name:'添加 SearchBar',exact:true}).click();
  await stack.getByRole('button',{name:'槽位 2',exact:true}).click();
  await page.getByRole('button',{name:'添加 Button',exact:true}).click();
  const search=stack.locator('[data-slot="children"]');
  const button=stack.locator('[data-slot="slot-1"]');
  let a=await search.boundingBox(),b=await button.boundingBox();
  assert(a&&b&&Math.abs(a.y-b.y)<2&&b.x>=a.x+a.width-1,'Editor slots must share a row');
  assert(a.width>b.width,'Search slot should fill remaining width');
  await stack.getByRole('button',{name:'槽位 2',exact:true}).click();
  await page.getByRole('button',{name:'布局',exact:true}).click();
  assert(await page.getByRole('button',{name:'删除槽位 2',exact:true}).isDisabled(),'Nonempty slot must not be deleted');
  await page.getByRole('button',{name:'＋ 添加槽位',exact:true}).click();
  await stack.getByRole('button',{name:'槽位 3',exact:true}).click();
  await page.getByRole('button',{name:'删除槽位 3',exact:true}).click();
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  assert.equal(await stack.locator('.stack-slot').count(),3);
  await page.getByRole('button',{name:'重做',exact:true}).click();
  assert.equal(await stack.locator('.stack-slot').count(),2);
  await page.getByRole('button',{name:'添加 Input',exact:true}).click();
  assert.equal(await page.getByRole('group',{name:'编辑 Input',exact:true}).count(),1,'Deleted insertion target must not block adding components');
  await page.getByRole('button',{name:'删除',exact:true}).click();
  const original=await downloadDsl();
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.getByText('已保存到本地',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('草稿已恢复',{exact:true}).waitFor();
  assert.deepEqual(await downloadDsl(),original,'IndexedDB restore must preserve complete DSL');
  await page.getByRole('button',{name:'预览',exact:true}).click();
  const runtime=page.locator('[data-component="layout.stack"]');
  a=await runtime.locator('[data-slot="children"]').boundingBox();b=await runtime.locator('[data-slot="slot-1"]').boundingBox();
  assert(a&&b&&Math.abs(a.y-b.y)<2&&b.x>=a.x+a.width-1,'Preview slots must share a row');
  await runtime.getByPlaceholder('搜索资源名称或描述…').fill('GitHub');
  assert.equal(await page.locator('tbody tr').count(),1);
  await runtime.getByRole('button',{name:'了解更多',exact:true}).click();
  await page.getByText('这是可配置的示例操作。',{exact:true}).waitFor();
  await runtime.getByRole('button',{name:'清除搜索',exact:true}).click();
  await runtime.getByRole('combobox',{name:'资源类型',exact:true}).selectOption('MCP');
  assert.equal(await page.locator('tbody tr').count(),2);
  await runtime.getByPlaceholder('搜索资源名称或描述…').fill('no-matching-resource');
  await page.getByText('没有找到匹配资源',{exact:true}).waitFor();
  assert.equal(await page.locator('tbody tr').count(),0);
  await runtime.getByRole('button',{name:'清除搜索',exact:true}).click();
  await runtime.getByRole('combobox',{name:'资源类型',exact:true}).selectOption('all');
  await page.getByRole('button',{name:'GitHub Connector',exact:true}).click();
  await page.locator('.resource-details h2').getByText('GitHub Connector',{exact:true}).waitFor();
  assert.equal(await page.locator('tbody tr[data-selected="true"]').count(),1);
  await page.getByRole('button',{name:'关闭详情',exact:true}).click();
  assert.equal(await page.locator('tbody tr[data-selected="true"]').count(),0);
  await page.getByRole('button',{name:'手机',exact:true}).click();
  a=await runtime.locator('[data-slot="children"]').boundingBox();b=await runtime.locator('[data-slot="slot-1"]').boundingBox();
  assert(a&&b&&b.y>=a.y+a.height-1,'Mobile slots must stack vertically');
  await page.getByRole('button',{name:'桌面',exact:true}).click();
  await page.getByRole('button',{name:'设计',exact:true}).click();
  await page.getByRole('button',{name:'新建',exact:true}).click();
  await page.getByRole('button',{name:'创建页面',exact:true}).click();
  await page.getByLabel('导入 Page DSL 文件').setInputFiles({name:'page.dsl.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(original))});
  await page.getByRole('button',{name:'确认导入',exact:true}).click();
  assert.deepEqual(await downloadDsl(),original,'DSL file round trip must preserve document');
  assert.equal(await page.locator(`[data-node-id="${id}"] .stack-slot`).count(),2);
  async function drag(handle,target){
    const start=await handle.boundingBox();assert(start);
    await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();
    await page.mouse.move(start.x+start.width/2+12,start.y+start.height/2+12,{steps:5});
    await target.waitFor({state:'visible'});await target.scrollIntoViewIfNeeded();
    const end=await target.boundingBox();assert(end);
    await page.mouse.move(end.x+end.width/2,end.y+end.height/2,{steps:20});await page.mouse.up();
  }
  await stack.getByRole('group',{name:'编辑 Button',exact:true}).hover();
  await drag(stack.getByRole('button',{name:'拖动 Button',exact:true}),page.getByTestId(`drop-${id}-children-1`));
  assert.equal((await downloadDsl()).root[0].slots.children[0].slots.children.length,2,'Cross-slot drag must move the button');
  await drag(page.getByRole('button',{name:'从组件库拖动 Input',exact:true}),page.getByTestId(`drop-${id}-slot-1-0`));
  assert.equal((await downloadDsl()).root[0].slots.children[0].slots['slot-1'][0].componentRef,'shadcn.input','Palette drag must target the selected slot');
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  assert.deepEqual(await downloadDsl(),original,'Undo must restore both drag operations');
  await stack.scrollIntoViewIfNeeded();
  await page.screenshot({path:'/tmp/composer-slots.png',fullPage:true});
  const response=await page.request.post(new URL('/api/export',page.url()).href,{data:{document:original,format:'code'}});
  assert(response.ok());const generated=await response.json();assert(generated.code.includes('slots={{'));assert(generated.code.includes('"slot-1"'));assert(!generated.code.includes('<StackSlot'));
  assert.deepEqual(errors,[]);
  console.log('PASS: palette and cross-slot drag, slot creation/removal/undo, horizontal layout, mobile layout, search/type filter/empty result/selection/detail close/button actions, IndexedDB restore, DSL download/import, generated code');
}catch(error){await page.screenshot({path:'/tmp/composer-slots-failure.png',fullPage:true});console.error(await page.locator('body').innerText());throw error;}finally{await browser.close();}
